apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployready
  labels: 
    app: myapp
    type: front-end
spec:
  template:

    metadata:
      name: myapp-pod
      labels: 
        app: myapp
        type: front-end
    spec: 
      containers:
        - name: nginx-container
          image: nginx-container
  selector:
    matchLabels:
      type: front-end  
  replicas: 4
