apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    name: ui-service
    app: taskmanager
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8083
      nodePort: 30006
  selector:
    name: ui-pod
    app: taskmanager
    