apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deploy
  labels:
    name: ui-deploy
    app: taskmanager
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: ui-pod
      app: taskmanager
  template:
    metadata:
      name: ui-pod
      labels:
        name: ui-pod
        app: taskmanager
    spec:
      containers:
        - name: taskmanager-angular-app
          image: nagaraj16/taskmanager_angular_app:release_1.0.1
          ports:
            - containerPort: 8083
          env:
            - name: API_URL
              value: "http://taskmanager-springboot-container:8081/api/tasks"
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: resource-volume
      volumes:
        - name: resource-volume
          hostPath:
              path: /usr/share/nginx/html
              type: Directory