apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
    app: taskmanager
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30007
  selector:
    name: api-pod
    app: taskmanager
    